name: airbridge
description: AirBridge spatial gesture-based encrypted file transfer prototype.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_webrtc: ^0.11.7
  web_socket_channel: ^2.4.0
  file_picker: ^8.1.6
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  uuid: ^4.5.1
  crypto: ^3.0.6
  multicast_dns: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

